bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 2048
debug: true
num_examples: 190

num_choices: 1


# Ссылки на документацию моделей


# a list of model to generate answers
model_list:
  - gpt-4o-mini
  - gpt-4o
  - o3-mini-2025-01-31
 



# oai like format


best_tgpt_checkpoint:
    model_name: './best_tgpt_checkpoint/'
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 6

o3-mini-2025-01-31:
    model_name: "o3-mini-2025-01-31"
    endpoints:
        - api_base: "https://openrouter.ai/api/v1"
          api_key: ""
    api_type: openai
    parallel: 6
    system_prompt: "You are a helpful math assistant. Answer in Russian."

gpt-4o:
    model_name: "gpt-4o"
    endpoints:
        - api_base: "https://openrouter.ai/api/v1"
          api_key: ""
    api_type: openai
    parallel: 6
    system_prompt: "You are a helpful math assistant. Answer in Russian."


gpt-4o-mini:
    model_name: "gpt-4o-mini"
    endpoints:
        - api_base: "https://openrouter.ai/api/v1"
          api_key: ""
    api_type: openai
    parallel: 6
    system_prompt: "You are a helpful math assistant. Answer in Russian."


